---
mcollective:
  # Our manifests support only 1 RabbitMQ broker at a time
  rabbitmq:
    vhost: /mcollective
    host: 192.168.100.104
    port: 61613
    user: mcollective
    password: marionette
  # Registration happens every 5 minutes using the Meta plugin
  registration:
    interval: 300
    plugin: Meta

apt:
  # Squid proxy on the management server
  proxy: 192.168.100.104:3128

sshd:
  authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOBLdzCDKR/yfyfdBlRxPsZzDFkPiiBmyaD7NeVZtshVCVvD8eLw1m5tyLaXQCXHj4rzwDNlgyT27MgxatrYOlEWUQuCkllTfocWyZRcNNol2UDnZ66DjVSJ8ideTNeRA3J5p+6Iajt2dXGPN2R8s7lF4TWOLLbescYQTSv1sTaO8K5ancH8FZgBgWTm3sSqpa3r7yHjQqplJwez8DGYoaxM1mXYe+H+ELPtmfwybdPSmaBl6ndOtn7iR2f4yODBDcXEdCQChYd4WaoxeL906Xgejgtb7tBdfNZCJ/bUazJhfv1+BFXbz5olTeUJiwMdskzWuOig4XCA/RW4LBCQaP bardasag@ksu.edu
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4jE/rjauBZ5xdfLU6H6WVvcIUE4kNVnUOG2slArFIDsnqvFkj6ZlAduHYm26R8rD/2TldscQ2PDTEj6c2lPzEnPvU0dFtqwKu7OjQ0wZG4y6ewVzyIH5AZGVr4NsqQM0gaAyyePVPcl5CEWvMoMQ6YrAGVx+ki0kuGikjQf30j9ku75ayxXOLTDIG0oZo4swbsZdVmnlxShHl3b/C4c39THHAWiejroc6JE5rApteqSMhYR8k0yrieG5zJgj52ys14I88tnQcyQisMHGcxQ8S0WLc0S783bc9DYIduY/glrQp/49T4UhijP2e/UqYngIxR2Olx+BnhuhTRnmm0z9v iunruh@spartan
