---
mcollective:
  # Our manifests support only 1 RabbitMQ broker at a time
  rabbitmq:
    vhost: /mcollective
    host: 172.16.200.140
    port: 61613
    user: mcollective
    password: marionette

# Squid proxy on the cloud gateway
apt::proxy_host: 172.17.0.6
apt::proxy_port: 3128
